import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1708380849235 implements MigrationInterface {
    name = 'Init1708380849235'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "travel_app"."answer_entity" ("id" SERIAL NOT NULL, "answer" character varying NOT NULL, "questionId" integer NOT NULL, "authorId" integer NOT NULL, CONSTRAINT "PK_3158283e703015676d2e7c7d862" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."question_entity" ("id" SERIAL NOT NULL, "question" character varying NOT NULL, "activityId" integer, "authorId" integer, CONSTRAINT "PK_14a0a509f33d8cd3a96a448dcd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."element_travel_photo_entity" ("id" SERIAL NOT NULL, "url" character varying NOT NULL, "elementTravelId" integer NOT NULL, CONSTRAINT "PK_03164aebaec1a4dc74b6f894851" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."accommodation_element_travel_photo_entity" ("id" SERIAL NOT NULL, "url" character varying NOT NULL, "elementTravelId" integer NOT NULL, CONSTRAINT "PK_b97dbaec2c84825003f86f738f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."accommodation_price_entity" ("id" SERIAL NOT NULL, "price" double precision NOT NULL, "startDate" date NOT NULL, "accommodationId" integer NOT NULL, CONSTRAINT "PK_e9523dbc01b535671d2669dc623" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."accommodation_rating_entity" ("id" SERIAL NOT NULL, "text" character varying NOT NULL, "authorId" integer NOT NULL, "accommodationId" integer NOT NULL, "elementTravelId" integer NOT NULL, "sharePhotos" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_9ab9f27e2252fae60ed5373927" UNIQUE ("elementTravelId"), CONSTRAINT "PK_b1aafa6e4a2061b53248baa9fd9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."accommodation_entity" ("id" SERIAL NOT NULL, "accepted" boolean NOT NULL, "name" character varying NOT NULL, "place" character varying NOT NULL, "description" character varying(5000) NOT NULL, "userId" integer NOT NULL, "deleteAt" TIMESTAMP, CONSTRAINT "PK_cdeb8f46445130b4ea60c7ead92" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."accommodation_element_travel_entity" ("id" SERIAL NOT NULL, "numberOfDays" integer NOT NULL, "price" double precision, "description" character varying(5000) NOT NULL, "travelId" integer NOT NULL, "accommodationId" integer NOT NULL, CONSTRAINT "PK_af09256c5ce6e03d0a51fca0677" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."accommodation_element_travel_instance_entity" ("id" SERIAL NOT NULL, "passed" boolean DEFAULT false, "travelInstanceId" integer NOT NULL, "accommodationId" integer NOT NULL, "elementTravelId" integer, "ratingId" integer, CONSTRAINT "REL_ea318754a7b8d3bfbda3269ac5" UNIQUE ("ratingId"), CONSTRAINT "PK_2366cfba91523c408dd2edf2225" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."travel_instance_entity" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "travelRecipeId" integer NOT NULL, "from" date NOT NULL, "to" date NOT NULL, CONSTRAINT "PK_a26c347a60e7a345edb36e609d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."element_travel_instance_entity" ("id" SERIAL NOT NULL, "passed" boolean DEFAULT false, "from" TIMESTAMP NOT NULL, "to" TIMESTAMP NOT NULL, "travelInstanceId" integer NOT NULL, "activityId" integer NOT NULL, "elementTravelId" integer, "ratingId" character varying, CONSTRAINT "PK_c04e47e83ea609405a5ceb49600" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."rating_entity" ("id" SERIAL NOT NULL, "text" character varying NOT NULL, "authorId" integer NOT NULL, "activityId" integer NOT NULL, "elementTravelId" integer NOT NULL, "sharePhotos" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_07a082914f04c2475175f7c4c3" UNIQUE ("elementTravelId"), CONSTRAINT "PK_86af853a9cd9ad9ec1ec6522eb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."price_entity" ("id" SERIAL NOT NULL, "price" double precision NOT NULL, "startDate" date NOT NULL, "activityId" integer NOT NULL, CONSTRAINT "PK_4d82b322ea6fb0f46f1de8cdd28" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."activity_parameter_entity" ("id" SERIAL NOT NULL, "value" character varying NOT NULL, "activityId" integer NOT NULL, "activityTypeParameterId" integer NOT NULL, CONSTRAINT "PK_bb9eaa14db5fa41b8b328cdac76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."activity_type_parameter_entity" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "activityTypeId" integer NOT NULL, CONSTRAINT "PK_1cb22421fd93996ef0611c45a7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."activity_type_entity" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_e39d1381c369f30443464ee8697" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."activity_entity" ("id" SERIAL NOT NULL, "accepted" boolean NOT NULL, "name" character varying NOT NULL, "description" character varying(5000) NOT NULL, "activityTypeId" integer NOT NULL, "userId" integer NOT NULL, "deleteAt" TIMESTAMP, CONSTRAINT "PK_ae8895d1732201c8184c61a24e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."element_travel_entity" ("id" SERIAL NOT NULL, "dayCount" integer NOT NULL, "from" TIME NOT NULL, "to" TIME NOT NULL, "price" double precision, "numberOfPeople" integer, "description" character varying(5000) NOT NULL, "travelId" integer NOT NULL, "activityId" integer NOT NULL, CONSTRAINT "PK_9576229d789a9c6b6e6a6c81dae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."travel_recipe_entity" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "countDays" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_5ffe1918f0bf088d229453e39df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."role_entity" ("id" SERIAL NOT NULL, "role" character varying NOT NULL, CONSTRAINT "PK_7bc1bd2364b6e9bf7c84b1e52e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."user_entity" ("id" SERIAL NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, CONSTRAINT "UQ_415c35b9b3b6fe45a3b065030f5" UNIQUE ("email"), CONSTRAINT "PK_b54f8ea623b17094db7667d8206" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_app"."answer_entity_likes_user_entity" ("answerEntityId" integer NOT NULL, "userEntityId" integer NOT NULL, CONSTRAINT "PK_40f5ff331daca46615d996c9610" PRIMARY KEY ("answerEntityId", "userEntityId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5dac1956ea42276ee35be6047" ON "travel_app"."answer_entity_likes_user_entity" ("answerEntityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb08852ca6fbe4a71fad1932f1" ON "travel_app"."answer_entity_likes_user_entity" ("userEntityId") `);
        await queryRunner.query(`CREATE TABLE "travel_app"."answer_entity_dislikes_user_entity" ("answerEntityId" integer NOT NULL, "userEntityId" integer NOT NULL, CONSTRAINT "PK_ea586d69b3316d7ba982377cdfe" PRIMARY KEY ("answerEntityId", "userEntityId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6e64a9ad472644001b7addefcd" ON "travel_app"."answer_entity_dislikes_user_entity" ("answerEntityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c1dd4ac538b527e860c789cb9" ON "travel_app"."answer_entity_dislikes_user_entity" ("userEntityId") `);
        await queryRunner.query(`CREATE TABLE "travel_app"."question_entity_likes_user_entity" ("questionEntityId" integer NOT NULL, "userEntityId" integer NOT NULL, CONSTRAINT "PK_112e7bc068d10e361825af3b053" PRIMARY KEY ("questionEntityId", "userEntityId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f8d916ca9f56058f13614bb73" ON "travel_app"."question_entity_likes_user_entity" ("questionEntityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7ed6d3ed77816091e07885a06" ON "travel_app"."question_entity_likes_user_entity" ("userEntityId") `);
        await queryRunner.query(`CREATE TABLE "travel_app"."question_entity_dislikes_user_entity" ("questionEntityId" integer NOT NULL, "userEntityId" integer NOT NULL, CONSTRAINT "PK_b3f4dfce1466d3ffcc9694ae675" PRIMARY KEY ("questionEntityId", "userEntityId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_41ae9903afe3798884754d6992" ON "travel_app"."question_entity_dislikes_user_entity" ("questionEntityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d14dc0327af7f9eb2269de28b" ON "travel_app"."question_entity_dislikes_user_entity" ("userEntityId") `);
        await queryRunner.query(`CREATE TABLE "travel_app"."role_entity_users_user_entity" ("roleEntityId" integer NOT NULL, "userEntityId" integer NOT NULL, CONSTRAINT "PK_140409a59b6cdb1d21f91880166" PRIMARY KEY ("roleEntityId", "userEntityId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71bc9edd8f7fe2cd3702f45a6e" ON "travel_app"."role_entity_users_user_entity" ("roleEntityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_42cf3453eccbf7f761b3468253" ON "travel_app"."role_entity_users_user_entity" ("userEntityId") `);
        await queryRunner.query(`CREATE TABLE "travel_app"."user_entity_roles_role_entity" ("userEntityId" integer NOT NULL, "roleEntityId" integer NOT NULL, CONSTRAINT "PK_9426d726a48f9c5d9c83c6eb91f" PRIMARY KEY ("userEntityId", "roleEntityId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3277e83a0656736e30b901d9a3" ON "travel_app"."user_entity_roles_role_entity" ("userEntityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_63f06698e4071b610eca2da812" ON "travel_app"."user_entity_roles_role_entity" ("roleEntityId") `);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity" ADD CONSTRAINT "FK_46f9a8790125a0d72234dda1614" FOREIGN KEY ("questionId") REFERENCES "travel_app"."question_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity" ADD CONSTRAINT "FK_3ea173bcc299b46513ae953fdf0" FOREIGN KEY ("authorId") REFERENCES "travel_app"."user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity" ADD CONSTRAINT "FK_f332b9dac22cf4b48c10139e71a" FOREIGN KEY ("activityId") REFERENCES "travel_app"."activity_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity" ADD CONSTRAINT "FK_1f1917a088f01f0cdbb7cf90829" FOREIGN KEY ("authorId") REFERENCES "travel_app"."user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_photo_entity" ADD CONSTRAINT "FK_cbcfaa9ed947c06052b8336675c" FOREIGN KEY ("elementTravelId") REFERENCES "travel_app"."element_travel_instance_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_photo_entity" ADD CONSTRAINT "FK_903b603cc0c469bb3ed50ae7234" FOREIGN KEY ("elementTravelId") REFERENCES "travel_app"."accommodation_element_travel_instance_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_price_entity" ADD CONSTRAINT "FK_f2af06530289854193a3b77ef5f" FOREIGN KEY ("accommodationId") REFERENCES "travel_app"."accommodation_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_rating_entity" ADD CONSTRAINT "FK_3ec4b05a7868a74e793e5d6f612" FOREIGN KEY ("authorId") REFERENCES "travel_app"."user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_rating_entity" ADD CONSTRAINT "FK_f988352b4c432a71254c9411606" FOREIGN KEY ("accommodationId") REFERENCES "travel_app"."accommodation_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_rating_entity" ADD CONSTRAINT "FK_9ab9f27e2252fae60ed53739274" FOREIGN KEY ("elementTravelId") REFERENCES "travel_app"."accommodation_element_travel_instance_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_entity" ADD CONSTRAINT "FK_ad24cbe8bc7e754d834c516a294" FOREIGN KEY ("userId") REFERENCES "travel_app"."user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_entity" ADD CONSTRAINT "FK_68597c76914d8981e7c0b140be5" FOREIGN KEY ("travelId") REFERENCES "travel_app"."travel_recipe_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_entity" ADD CONSTRAINT "FK_d00bcff369f0ebd0d95a0ff8d4f" FOREIGN KEY ("accommodationId") REFERENCES "travel_app"."accommodation_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_instance_entity" ADD CONSTRAINT "FK_db6b07427c2ced213a739e39971" FOREIGN KEY ("travelInstanceId") REFERENCES "travel_app"."travel_instance_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_instance_entity" ADD CONSTRAINT "FK_4e800ddbf2e6c9108a5dffd8744" FOREIGN KEY ("accommodationId") REFERENCES "travel_app"."accommodation_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_instance_entity" ADD CONSTRAINT "FK_fb68c2637670d7a74f4926ce0be" FOREIGN KEY ("elementTravelId") REFERENCES "travel_app"."accommodation_element_travel_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_instance_entity" ADD CONSTRAINT "FK_ea318754a7b8d3bfbda3269ac59" FOREIGN KEY ("ratingId") REFERENCES "travel_app"."accommodation_rating_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."travel_instance_entity" ADD CONSTRAINT "FK_8530e30f832c6b3a886e5f9144d" FOREIGN KEY ("userId") REFERENCES "travel_app"."user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."travel_instance_entity" ADD CONSTRAINT "FK_7dddab5bf81b05aa5424b4c8bc4" FOREIGN KEY ("travelRecipeId") REFERENCES "travel_app"."travel_recipe_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_instance_entity" ADD CONSTRAINT "FK_4e9f5c0b5e3df24af79b9561390" FOREIGN KEY ("travelInstanceId") REFERENCES "travel_app"."travel_instance_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_instance_entity" ADD CONSTRAINT "FK_7148478949cf239738ff15a058a" FOREIGN KEY ("activityId") REFERENCES "travel_app"."activity_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_instance_entity" ADD CONSTRAINT "FK_916a30182e3e4d5bb8343de8649" FOREIGN KEY ("elementTravelId") REFERENCES "travel_app"."element_travel_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."rating_entity" ADD CONSTRAINT "FK_e47333507643de077e28070b2cc" FOREIGN KEY ("authorId") REFERENCES "travel_app"."user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."rating_entity" ADD CONSTRAINT "FK_1f441fa9463732a1486674087ac" FOREIGN KEY ("activityId") REFERENCES "travel_app"."activity_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."rating_entity" ADD CONSTRAINT "FK_07a082914f04c2475175f7c4c36" FOREIGN KEY ("elementTravelId") REFERENCES "travel_app"."element_travel_instance_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."price_entity" ADD CONSTRAINT "FK_86eb55926363db21706185beac4" FOREIGN KEY ("activityId") REFERENCES "travel_app"."activity_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."activity_parameter_entity" ADD CONSTRAINT "FK_19b3fe6c052c7170bd2505d7b47" FOREIGN KEY ("activityId") REFERENCES "travel_app"."activity_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."activity_parameter_entity" ADD CONSTRAINT "FK_237695feda31ed013fa6549da13" FOREIGN KEY ("activityTypeParameterId") REFERENCES "travel_app"."activity_type_parameter_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."activity_type_parameter_entity" ADD CONSTRAINT "FK_eb71e8144af9001f872034f15d3" FOREIGN KEY ("activityTypeId") REFERENCES "travel_app"."activity_type_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."activity_entity" ADD CONSTRAINT "FK_843abecad99ab52b315a43426d3" FOREIGN KEY ("activityTypeId") REFERENCES "travel_app"."activity_type_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."activity_entity" ADD CONSTRAINT "FK_560b68cd00b521eaa461d2f03e6" FOREIGN KEY ("userId") REFERENCES "travel_app"."user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_entity" ADD CONSTRAINT "FK_0f1509b9323cdf5ea6c5bec08df" FOREIGN KEY ("travelId") REFERENCES "travel_app"."travel_recipe_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_entity" ADD CONSTRAINT "FK_a7f0ef67ae13c818a9291661f9e" FOREIGN KEY ("activityId") REFERENCES "travel_app"."activity_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."travel_recipe_entity" ADD CONSTRAINT "FK_51ef974933f48f1cab825efec8c" FOREIGN KEY ("userId") REFERENCES "travel_app"."user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity_likes_user_entity" ADD CONSTRAINT "FK_b5dac1956ea42276ee35be6047d" FOREIGN KEY ("answerEntityId") REFERENCES "travel_app"."answer_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity_likes_user_entity" ADD CONSTRAINT "FK_fb08852ca6fbe4a71fad1932f12" FOREIGN KEY ("userEntityId") REFERENCES "travel_app"."user_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity_dislikes_user_entity" ADD CONSTRAINT "FK_6e64a9ad472644001b7addefcda" FOREIGN KEY ("answerEntityId") REFERENCES "travel_app"."answer_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity_dislikes_user_entity" ADD CONSTRAINT "FK_2c1dd4ac538b527e860c789cb98" FOREIGN KEY ("userEntityId") REFERENCES "travel_app"."user_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity_likes_user_entity" ADD CONSTRAINT "FK_7f8d916ca9f56058f13614bb733" FOREIGN KEY ("questionEntityId") REFERENCES "travel_app"."question_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity_likes_user_entity" ADD CONSTRAINT "FK_a7ed6d3ed77816091e07885a063" FOREIGN KEY ("userEntityId") REFERENCES "travel_app"."user_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity_dislikes_user_entity" ADD CONSTRAINT "FK_41ae9903afe3798884754d69920" FOREIGN KEY ("questionEntityId") REFERENCES "travel_app"."question_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity_dislikes_user_entity" ADD CONSTRAINT "FK_2d14dc0327af7f9eb2269de28b5" FOREIGN KEY ("userEntityId") REFERENCES "travel_app"."user_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "travel_app"."role_entity_users_user_entity" ADD CONSTRAINT "FK_71bc9edd8f7fe2cd3702f45a6ed" FOREIGN KEY ("roleEntityId") REFERENCES "travel_app"."role_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "travel_app"."role_entity_users_user_entity" ADD CONSTRAINT "FK_42cf3453eccbf7f761b3468253f" FOREIGN KEY ("userEntityId") REFERENCES "travel_app"."user_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "travel_app"."user_entity_roles_role_entity" ADD CONSTRAINT "FK_3277e83a0656736e30b901d9a30" FOREIGN KEY ("userEntityId") REFERENCES "travel_app"."user_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "travel_app"."user_entity_roles_role_entity" ADD CONSTRAINT "FK_63f06698e4071b610eca2da812c" FOREIGN KEY ("roleEntityId") REFERENCES "travel_app"."role_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "travel_app"."user_entity_roles_role_entity" DROP CONSTRAINT "FK_63f06698e4071b610eca2da812c"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."user_entity_roles_role_entity" DROP CONSTRAINT "FK_3277e83a0656736e30b901d9a30"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."role_entity_users_user_entity" DROP CONSTRAINT "FK_42cf3453eccbf7f761b3468253f"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."role_entity_users_user_entity" DROP CONSTRAINT "FK_71bc9edd8f7fe2cd3702f45a6ed"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity_dislikes_user_entity" DROP CONSTRAINT "FK_2d14dc0327af7f9eb2269de28b5"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity_dislikes_user_entity" DROP CONSTRAINT "FK_41ae9903afe3798884754d69920"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity_likes_user_entity" DROP CONSTRAINT "FK_a7ed6d3ed77816091e07885a063"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity_likes_user_entity" DROP CONSTRAINT "FK_7f8d916ca9f56058f13614bb733"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity_dislikes_user_entity" DROP CONSTRAINT "FK_2c1dd4ac538b527e860c789cb98"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity_dislikes_user_entity" DROP CONSTRAINT "FK_6e64a9ad472644001b7addefcda"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity_likes_user_entity" DROP CONSTRAINT "FK_fb08852ca6fbe4a71fad1932f12"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity_likes_user_entity" DROP CONSTRAINT "FK_b5dac1956ea42276ee35be6047d"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."travel_recipe_entity" DROP CONSTRAINT "FK_51ef974933f48f1cab825efec8c"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_entity" DROP CONSTRAINT "FK_a7f0ef67ae13c818a9291661f9e"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_entity" DROP CONSTRAINT "FK_0f1509b9323cdf5ea6c5bec08df"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."activity_entity" DROP CONSTRAINT "FK_560b68cd00b521eaa461d2f03e6"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."activity_entity" DROP CONSTRAINT "FK_843abecad99ab52b315a43426d3"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."activity_type_parameter_entity" DROP CONSTRAINT "FK_eb71e8144af9001f872034f15d3"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."activity_parameter_entity" DROP CONSTRAINT "FK_237695feda31ed013fa6549da13"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."activity_parameter_entity" DROP CONSTRAINT "FK_19b3fe6c052c7170bd2505d7b47"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."price_entity" DROP CONSTRAINT "FK_86eb55926363db21706185beac4"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."rating_entity" DROP CONSTRAINT "FK_07a082914f04c2475175f7c4c36"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."rating_entity" DROP CONSTRAINT "FK_1f441fa9463732a1486674087ac"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."rating_entity" DROP CONSTRAINT "FK_e47333507643de077e28070b2cc"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_instance_entity" DROP CONSTRAINT "FK_916a30182e3e4d5bb8343de8649"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_instance_entity" DROP CONSTRAINT "FK_7148478949cf239738ff15a058a"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_instance_entity" DROP CONSTRAINT "FK_4e9f5c0b5e3df24af79b9561390"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."travel_instance_entity" DROP CONSTRAINT "FK_7dddab5bf81b05aa5424b4c8bc4"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."travel_instance_entity" DROP CONSTRAINT "FK_8530e30f832c6b3a886e5f9144d"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_instance_entity" DROP CONSTRAINT "FK_ea318754a7b8d3bfbda3269ac59"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_instance_entity" DROP CONSTRAINT "FK_fb68c2637670d7a74f4926ce0be"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_instance_entity" DROP CONSTRAINT "FK_4e800ddbf2e6c9108a5dffd8744"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_instance_entity" DROP CONSTRAINT "FK_db6b07427c2ced213a739e39971"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_entity" DROP CONSTRAINT "FK_d00bcff369f0ebd0d95a0ff8d4f"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_entity" DROP CONSTRAINT "FK_68597c76914d8981e7c0b140be5"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_entity" DROP CONSTRAINT "FK_ad24cbe8bc7e754d834c516a294"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_rating_entity" DROP CONSTRAINT "FK_9ab9f27e2252fae60ed53739274"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_rating_entity" DROP CONSTRAINT "FK_f988352b4c432a71254c9411606"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_rating_entity" DROP CONSTRAINT "FK_3ec4b05a7868a74e793e5d6f612"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_price_entity" DROP CONSTRAINT "FK_f2af06530289854193a3b77ef5f"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."accommodation_element_travel_photo_entity" DROP CONSTRAINT "FK_903b603cc0c469bb3ed50ae7234"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."element_travel_photo_entity" DROP CONSTRAINT "FK_cbcfaa9ed947c06052b8336675c"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity" DROP CONSTRAINT "FK_1f1917a088f01f0cdbb7cf90829"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."question_entity" DROP CONSTRAINT "FK_f332b9dac22cf4b48c10139e71a"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity" DROP CONSTRAINT "FK_3ea173bcc299b46513ae953fdf0"`);
        await queryRunner.query(`ALTER TABLE "travel_app"."answer_entity" DROP CONSTRAINT "FK_46f9a8790125a0d72234dda1614"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_63f06698e4071b610eca2da812"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_3277e83a0656736e30b901d9a3"`);
        await queryRunner.query(`DROP TABLE "travel_app"."user_entity_roles_role_entity"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_42cf3453eccbf7f761b3468253"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_71bc9edd8f7fe2cd3702f45a6e"`);
        await queryRunner.query(`DROP TABLE "travel_app"."role_entity_users_user_entity"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_2d14dc0327af7f9eb2269de28b"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_41ae9903afe3798884754d6992"`);
        await queryRunner.query(`DROP TABLE "travel_app"."question_entity_dislikes_user_entity"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_a7ed6d3ed77816091e07885a06"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_7f8d916ca9f56058f13614bb73"`);
        await queryRunner.query(`DROP TABLE "travel_app"."question_entity_likes_user_entity"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_2c1dd4ac538b527e860c789cb9"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_6e64a9ad472644001b7addefcd"`);
        await queryRunner.query(`DROP TABLE "travel_app"."answer_entity_dislikes_user_entity"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_fb08852ca6fbe4a71fad1932f1"`);
        await queryRunner.query(`DROP INDEX "travel_app"."IDX_b5dac1956ea42276ee35be6047"`);
        await queryRunner.query(`DROP TABLE "travel_app"."answer_entity_likes_user_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."user_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."role_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."travel_recipe_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."element_travel_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."activity_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."activity_type_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."activity_type_parameter_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."activity_parameter_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."price_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."rating_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."element_travel_instance_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."travel_instance_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."accommodation_element_travel_instance_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."accommodation_element_travel_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."accommodation_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."accommodation_rating_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."accommodation_price_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."accommodation_element_travel_photo_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."element_travel_photo_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."question_entity"`);
        await queryRunner.query(`DROP TABLE "travel_app"."answer_entity"`);
    }

}
